# 当前配置文件放公共配置或者默认配置

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 1MB
      maxRequestSize: 10MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    #日期格式化
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_NULL
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true


##### client & service 公用配置 #####

# Tomcat specifics
server:
  tomcat:
    basedir: ./temp
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    background-processor-delay: 30s
    accesslog:
      enabled: false

##### client  #####
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 240000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true


#### 系统建康状态 #####
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      contextPath: /
    ssl:
      enabled: false
  endpoint:
    health:
      showDetails: always
    shutdown:
      enabled: true
    restart:
      enabled: true